### ISSUE TITLE
Pasting from Windows to Codespaces Terminal doesn't work

### ISSUE THREAD

**Issue by matsonj** [tconbeer/textual-textarea#120]
When running Harlequin inside a Codespaces Terminal, copy-pasting does not work when moving into and out of the codespace.

for example - the snippet `select 1 as test`:

- [x] from windows -> WSL terminal
- [x] from windows -> WSL terminal, ssh connected to codespace
- [ ] from windows -> WSL terminal, ssh connected to codespace, running harlequin

I've added `xsel` and `xclip` to my docker image, but neither appears to do anything. "Out of the box" Windows Terminal running Ubuntu inside WSL copy+paste works seamlessly.

**Comment by tconbeer** [comment]
ok, so I've fixed paste in  my new branch, using the terminals' native Paste message. If ctrl+v doesn't fire that message, right clicking or pressing `shift+insert` should.

It looks to me like xclip and xsel don't work inside of codespaces, which could be part of the problem. (even after installing those libraries, pyperclip can't seem to locate or use them).
